#ifndef LLIST_H
#define LLIST_H
#include "redef.h"

RECORD LLIST
{ CHAR*CONTENT;
  RECORD DLLIST*NEXT;
  U64 LEN;
  U32 INDEX;
};

TYPEDEF RECORD LLIST LLIST;

VOID ADD_NEXT(LLIST*LINES, CHAR*CONTENT, U64 LEN, U32 INDEX);

VOID ADD_CURRENT(LLIST*LINES, CHAR*CONTENT, U64 LEN, U32 INDEX);

VOID DEL_CURRENT(LLIST*LINES, U32 INDEX);

#endif
